### ISSUE TITLE
How shall we recommend the submission be made visible to the public?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#10]
The prior version of the guidelines described using obsolete wiki systems, etc. Do we want to prescribe some "official" mechanism like the TDWG website for making the submission available, or offer several suggestions such as the group's Github repo, or make no suggestions and just tell the review manager that the submission needs to be publicly visible?

**Comment by baskaufs** [comment]
Relevant sections of document:

[Section 4 Public Review, line 129](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)

**Comment by baskaufs** [comment]
Comments captured from the Google doc:

Baskauf: This section needs to be updated based on current practice. At a minimum, the files need to be made easily visible to the public in their revised form. Typically, they will end up being in Markdown so that they can display on the TDWG website or at some other location in GitHub. I don't know if we need to say that it's a requirement that the authors provide the final draft for review as Markdown in GitHub. Typically, that's how it's been done, but I could easily see a specification being worked out as a Google Doc or Word doc then passed on to the reviewers in that form. In that case, is it the author's job to turn that into Markdown? The review manager's job? Or is that something we leave up to the review manager and not specify here?

Belbin: I'd suggest that providing some consistency (a standard :) for the final form and whose responsibility that is. Any interim documents can follow anything that the process and people involved find useful.

Endresen: If specific, maybe it better to use a generic term such as "wordprocessor" than "Word" (or "Google Doc"). However, would a Markdown be covered by the term "wordprocessor"? And apropos, how sure are we Markdown will stand the test of time?

Baskauf: I wouldn't include Markdown under the "wordprocessor" category, although you might be able to export from some word processors in that format. As for the sustainability of Markdown, it is really a very simple text markup language. So even if one did not know how to interpret the formatting commends, the content is completely readable.

Endresen: Yes, but I mean if Markdown was to be indicated as the recommended format - how sure are we that Markdown a few years from now would not be replaced by another best practice format? (XML is no longer modern - yet simple to read in plain text).

However, more important these guidelines frequently suggest MS Word as document format - which looks very outdated today...

**Comment by gkampmeier** [comment]
I agree with Belbin's comment above for interim documents following whatever current process appears useful. The longevity of other formats, however is questionable, and to me, the term "word processor" takes me back to the 1980s and the ABDick dedicated word processors that caused older secretaries to retire (despairing over the learning curve). Nostalgia aside, one of the purposes of starting _[Biodiversity Information Science and Standards (BISS)](https://biss.pensoft.net/)_ was to publish our standards (and papers about our standards) in an open access, persistent (with DOI) fashion. Arguably, this is where we should be publishing our standards, although TDWG may have to pay for their publication. @jmacklin @stanblum @debpaul

**Comment by dagendresen** [comment]
I love the suggestion to publish the submission in BISS -- for a public review (the version of the submission after the expert review is approved) -- leading to a final version published persistently in BISS. [The public review process could still be complemented by e.g. GitHub based on the decision of the Review Manager?]

If there is a cost issue -- maybe Zenodo could be an alternative? ... or simply for the authors of the new standard to pay the BISS publishing fee...?

**Comment by baskaufs** [comment]
In https://github.com/tdwg/process/commit/088535e276711c912018863948f29ebce48b66b2 I approached this issue in lines 125-133 by describing the required features of the publicly viewable submission rather than prescribing the platform. For that, I just said "according to current TDWG practice". 

I think this is the best approach to take at the moment given two factors:
- at least one standard (the Collections Description, a.k.a. Santiago Core) is probably weeks away from submission and we need this document to be done.
- reaching a decision about whether to publish in BISS or somewhere else will probably take longer than that.

I'm also just not convinced that we need to write a venue into guidelines like this.

**Comment by gkampmeier** [comment]
I would like to leave it as a suggestion in the documentation so that people think about BISS as something other than just for conference abstracts.  We have a standards category [https://biss.pensoft.net/about](https://biss.pensoft.net/about) as well as others. I tried to get this across in the [blog post](https://blog.pensoft.net/2021/07/13/not-your-typical-conference-abstract-tdwg2021/).

**Comment by baskaufs** [comment]
@gkampmeier how about something like this: https://github.com/tdwg/process/commit/4e06a424fb5c0125dbd5d28093d40d0c3f7005ec
