### ISSUE TITLE
Capitalization for reserved words

### ISSUE THREAD

**Issue by dagendresen** [tdwg/process#13]
Some reserved words (made into proper nouns) were inconsistently capitalized in only some parts of the document, while written in lowercase in other parts.

I have tried to go through to capitalize - where this was missing -- in [revisions_round1/review_manager.md](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md)
* Standard
* Review
* Review Manager
* Reviewer
* Public Review

I did not capitalize inside the abstract nor example email. Should we do these also?

**Comment by gkampmeier** [comment]
It may depend on context. These should only be capitalized when referring to the standard, review, review manager, reviewer, or public review in question, but not the process in general.

**Comment by dagendresen** [comment]
@gkampmeier thanks! I have restored most words, however, there remain some formatting I am unsure of.
