### ISSUE TITLE
Should expert reviews be kept private or made public

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#3]
Notes from the revision of the Review Manager guidelines:

Steve: In the OJS system, there was a conflict with what was said in the previous section about reviewers being anonymous to all but the review manager. They were not - anyone with editing privileges could look at any previous review. There was a change of review managers and it was highly useful for me to have seen what the previous manager had done so far. Perhaps in the current state of affairs, the appropriate place to keep the records relating to the expert review would be in a private GitHub repo. Access to that repo could be to a designated "team" whose members could be added and removed as necessary

Lee: It would seem wise to have review comments 'private' until the review is completed. Is there any reason that all review comments and documents could not be made public post review? This would also tend to better ensure information was not lost and would be available to review managers and reviewers subsequently.

**Comment by gkampmeier** [comment]
In many review settings, reviewers have the choice of being anonymous or not (my personal preference would be that they would check "not" in open science, but I understand with GDPR and other considerations, that this is not always possible).  Is this past our capabilities? I would generally like to a) see people acknowledged for their contributions; b) encourage civility/constructiveness of reviews by making them open.

**Comment by baskaufs** [comment]
I don't think there is really any reason why a reviewer would have to remain anonymous and the point about acknowledging contributions is a good one.  However, I think this is also balanced by the point that anonymity can promote candidness. Particularly in a situation like TDWG, which is a rather small community, it is likely that reviewers may be friends or past collaborators with members of the task group and that could make critical reviews awkward. As you say, we should encourage civility/constructiveness, though.

I think the solution may be to allow the solicited reviewer to choose whether to remain anonymous or not.

**Comment by gkampmeier** [comment]
I would agree, and I know that there are some instances where reviewers do/would not feel comfortable submitting a critical review (particularly of someone more senior in a hierarchy or in certain political situations), so best of both worlds would be to have that choice.  Is it possible to set that up in GitHub when presumably you need to have an account to contribute? Or would that require using some other platform?

**Comment by baskaufs** [comment]
I don't know what kind of mechanisms could be set up but I would guess the simple solution would be for the review manager to just manage the confidentiality part. I think if there were a private repository, documents and a record of correspondence could be put there manually and we could probably assume that people who have access would have the judgement to examine only the documents they have business to examine. For items later to be made public, I suppose the review manager could just manually scrub them of anything confidential. I think that would be relatively easy for text copy/paste (e.g. Markdown) but if, for example, a Word doc, or pdf made from a Word doc were posted, more care would be needed to scrub the invisible metadata.

**Comment by baskaufs** [comment]
Relevant to this issue: Here is a summary @dagendresen made of the expert reviews for SDS/VMS <https://github.com/tdwg/vocab/blob/master/expert-review-materials/TDWG-VOCAB-expert-review-report-v20161113.pdf>

Full reviews listed, but with reviewer names redacted.

**Comment by baskaufs** [comment]
I don't think that I released anything similar for Audubon Core. The reviews were uploaded to OJS, but I suppose they were lost when OJS was decommissioned. But I don't think they were made public (although the public review comments were, at <https://github.com/tdwg/ac/blob/master/historical/RecordOfPublicReview.md> except for confidential ones.)

**Comment by dagendresen** [comment]
1) Might requesting all reviewers to contribute through GitHub be a barrier? Not all in our community are on GitHub, nor familiar with how to use this platform.
2) Full review correspondence might be verbose or in other ways less useful to revisit than a summary report made by the review manager. The full review correspondence might include side conversations about the "weather", or larger news events irrelevant to the peer review. A summary report could be much more focused and condensed.
3) If peer review contributions are completely open real-time, the other peer-reviewers would likely read each other comments and not deliver independent peer reviews?
4) There might perhaps be a parallel open comment option - with the volunteer option for the invited peer-reviewers to comment openly? Which might also kick-start the public comment process...

**Comment by dagendresen** [comment]
5) OJS was discontinued, Google Code was discontinued, maybe also GitHub will be discontinued. Putting too much trust in a communication platform to be maintained seems risky.

**Comment by baskaufs** [comment]
Relevant sections of document are:

[Section 5.2 Example of an email to potential reviewers, line 197](https://github.com/tdwg/process/blob/master/review_manager.md#52-example-of-an-email-to-potential-reviewers) 

Also address the issue of whether anonymity is required or desirable, see [item 1 Independent Reviewers in Section 1.3, line 54](https://github.com/tdwg/process/blob/master/review_manager.md#13-independent-reviewers)

**Comment by dagendresen** [comment]
I lean towards simply maintaining the expert review anonymous (by default), and outside GitHub "memory". And simply to specify rather as few details as possible for HOW this expert review is to be coordinated by the Review Manager. But require the Review Manager to write and release a report from the expert review with the announcement of the public review? _The expert reviewers could themselves disclose their identity through comments made in the public review period - if they so choose??_

Apropos the BISS suggestion from @gkampmeier https://github.com/tdwg/process/issues/10#issuecomment-800299782 - if making the review in BISS maybe Pensoft has appropriate tools available for the Review Manager to use??

**Comment by baskaufs** [comment]
I think the BISS idea is promising and may be the way to go. However, it is reminding me a lot of the original document, which in which the defunct OJS system was deeply embedded. I guess if we recommend the BISS system and it goes away like OJS did, we can just rewrite the document again. But it seems like there should be some separation. 

Maybe describe the general process and principles in the main document, and then isolate into an Appendix the details of managing the exposure and review process via BISS.

**Comment by dagendresen** [comment]
Proposed the following lines to the email template (see [revisions_round1/review_manager.md](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md))
> Submission materials for review will be made available pending your acceptance to undertake this task. Notice that the anonymous expert review is followed by a public review period. More information about the TDWG review process is available at {link-to-this-document}.

> Please disclose if you have a conflict of interest with the content of the manuscript or the authors.

**Comment by gkampmeier** [comment]
Unlike OJS, BISS articles have a DOI that should be resolvable into the future, even if BISS itself goes away or becomes folded into something else. It is TDWG's journal. It is also supported by a major publisher of many journals (Pensoft). OJS issues had an ISBN (sometimes, for the Proceedings), but individual articles never had any persistent identifiers.  Yes, we can rewrite/update the guidelines (they probably need to be revisited at least once a decade anyway ;), but this would seem a major step forward into something easily accessible to a broader audience, indexed and easily citable.

**Comment by gkampmeier** [comment]
@dagendresen do we need to define what we mean by a "conflict of interest" (a rabbit hole) or indicate: "Please disclose if you have a conflict of interest _that would lead you to a biased review of_ the content of the manuscript or _would make you unable to distance yourself from a relationship with one or more of_ the authors." In this way, if the person feels that they have a conflict of interest, then they should recuse themselves or ask for further guidance.

**Comment by Tasilee** [comment]
As per https://github.com/tdwg/process/issues/5#issuecomment-800641414, I would default to everything being public unless specifically requested to be anonymous. There may be cases where there is 'private' communication between the Review Manager and reviewers/commenters but let's leave that to the RM.

Regarding "conflict of interest", like 'open by default', should be encouraged, but stated explicitly, at least to the Review Manager. In other words, TDWG should encourage all comments, even where there may be conflict of interest as the submissions may be valuable in achieving a good outcome. In some cases, the identity of the reviewer/comments will be sufficient to make potential conflict obvious, but in others, far less so. Ideally, the Review Manager needs to know that there is a 'conflict of interest'. Having some form of check for potential conflicts on submission seems (a legal :) necessity, but should not veto submissions.

**Comment by gkampmeier** [comment]
@Tasilee I think my comments about conflict of interest were more for the Independent Reviewers than the public review. I too think that anonymous should be rare and dealt with by the Review Manager.

**Comment by dagendresen** [comment]
Maybe the Review Managers report could also be published in BISS with an invitation to the Expert Reviewers as co-authors?

**Comment by baskaufs** [comment]
There seems to be a consensus that the expert reviewers should have the option to either remain anonymous or identify themselves in their reviews. Please examine the changes I made as shown in [this diff](https://github.com/tdwg/process/commit/4af64be98c52978454ffac3c40515e7fcf908f6c#diff-1b571d9e461845b8613559351ada73c70991f9bea2a95500c10d2bb50bd0cd4b) and feel free to reword.

I did not go into detail about what "carrots" would be made available if reviewers choose not to be anonymous. I just said "your contribution will be recognized when the standard is published". I've been trying to add information in the standards metadata that includes the review managers as contributors to the standard and there is no reason why the reviewers can't be similarly acknowledged. Whether that's just on the standards landing page or in some more formal publication can be worked out later and I don't think it needs to be detailed here. 

I added a brief elaboration in line 244 about COI -- please assess whether more needs to be said than that in order to clarify. 

I am not yet going to close this issue since it has a lot of moving parts, but if I get several "thumbs up" after you've had a chance to review the changes, I'll close it.

**Comment by gkampmeier** [comment]
line 58 The option to remain anonymous should be available to the reviewers in order to promote candidness. However, in the interest of supporting open science and to recognize their contributions, the reviewers may choose to identify themselves when they submit their reviews.

This doesn't make clear what the default is. I would prefer that we flip the statements: "In the interest of supporting open science and to recognize their contributions, reviewers will be identified when they submit their reviews. However the option to remain anonymous will be available to the reviewers in order to promote candidness."

**Comment by baskaufs** [comment]
@gkampmeier I have changed the draft to incorporate your suggestion.

**Comment by Tasilee** [comment]
I'd also prefer the default open position. It needs to be reinforced regularly.

**Comment by dagendresen** [comment]
I support open expert reviews as the default, however, reluctant to use language to actively discourage/influence expert reviewers away from selecting an anonymous review submission.

**Comment by baskaufs** [comment]
@dagendresen Is the current text acceptable to you? We could soften the text slightly by saying something like:

> In the interest of supporting open science and to recognize their contributions, reviewers will be identified *by default* when they submit their reviews. However the option to remain anonymous will be available to the reviewers in order to promote candidness.

(italics wouldn't be in the actual text). That makes the "will" a little less strong.

**Comment by baskaufs** [comment]
I think everything here has been addressed through https://github.com/tdwg/process/commit/46448fdf4914754eff086d28d9e08a69d56b6fdc
