### ISSUE TITLE
Must comments in public review be made public?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#4]
The review manager guidelines are inconsistent on this. On page 8 it says:

> Public Review comments in OJS are openly visible to all. The Author can be examining comments, discussing issues with the Review Manager, and preparing responses or changes once the first comment is posted. 
> 
> An issue tracking system can be used in addition to, or as an alternative to the OJS comments/feedback in the public review. The basic requirement is that
> 
> The public can view and easily comment on the proposal
> That all comments can be identified to an individual with at least an email address

but on page 11 it says:

> Comments can be anonymous by selecting ‘post this comment anonymously’ checkbox on the comment form. 

In the past, I believe that review managers have indicated that persons who wish for their comments to be private could email them directly to the review manager.

**Comment by dagendresen** [comment]
The (text of the) "public review comments" can be made openly visible to all, even if the identity of the person making the comment is not. The guidelines could allow for both anonymous comments communicated through the review manager and signed comments submitted directly by the commenter.

Another rationale for the review comments to be openly visible to all (yet anonymous if desired) could be for the expert reviewers to verify that their comments have been accurately presented. In short, there could be a rationale for both openly visible comments and the option to communicate comments anonymously (but via the review manager).

Another question could be: _Must the expert review comments be anonymous?_ Would we want to suggest listing the names of the three experts -- at their own choice/request?

And next, one can imagine the expert review comments to be anonymous only during the expert peer review period (and public peer review period) and then be made signed?

**Comment by gkampmeier** [comment]
See [comment on Issue 5](https://github.com/tdwg/process/issues/5#issuecomment-778630951).  

Regarding whether expert (i.e., Independent) reviews be anonymous, I fall on the side of encouraging making them public and allowing them to take credit (on Publons, ORCID etc.)--proper reviewing is hard work and should be acknowledged, but offering the option of anonymity.  In either case, this would be a required field.

**Comment by baskaufs** [comment]
Relevant sections of the document are:

[Section 3.3 Post Review, line 117](https://github.com/tdwg/process/blob/master/review_manager.md#33-post-review)

[Section 4 Public Review, line 144 and following lines](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)

**Comment by baskaufs** [comment]
Discussion captured from the Google doc:

Baskauf: In the OJS system, there was a conflict with what was said in the previous section about reviewers being anonymous to all but the review manager. They were not - anyone with editing privileges could look at any previous review. There was a change of review managers and it was highly useful for me to have seen what the previous manager had done so far. Perhaps in the current state of affairs, the appropriate place to keep the records relating to the expert review would be in a private GitHub repo. Access to that repo could be to a designated "team" whose members could be added and removed as necessary.

Belbin: It would seem wise to have review comments 'private' until the review is completed. Is there any reason that all review comments and documents could not be made public post review? This would also tend to better ensure information was not lost and would be available to review managers and reviewers subsequently.

Endresen: It might be useful to offer the reviewers the option to provide anonymous comments to ensure they are not restricted in any way by making comments completely public? A good summary report including all (anonymous) reviewer comments might also give a better overview than all raw comments?

Kampmeier: In reviews of journal articles, reviewers are often given the opportunity to address additional comments to the review manager (editor), which are not directly seen by the authors, but which may be used by the review manager in the justification of any decision. This is why a form is desirable for reviewers, but the ultimate storage (for archival purposes) might be something like GitHub.

**Comment by baskaufs** [comment]
More discussion from the Google doc:

Baskauf: As I said in an email, is it acceptable to have anonymous comments or concerns expressed directly to the review manager? Are Public Reviews "public" because they are made by members of the public, or because they are public (i.e. open)? I believe that in at least one public review, the review announcement said that confidential comments could be made by email directly to the review manager.

Belbin: I agree Steve. There needs to be a distinction made about the need for confidential or anonymous comments in a public review.

Endresen: "Review comments" CAN BE both openly visible to all and anonymous.

**Comment by baskaufs** [comment]
Another thread from the Google doc:

Baskauf: When the GitHub issues tracker is used, the commenters are identified by their username, which I guess is good enough. However, there probably really needs to be another alternative to GitHub for users who can't or don't want to get GitHub accounts. I can't remember exactly what is required to comment on issue, but there may be a necessity to check the settings since I've heard complaints from people who have tried and failed to use the GitHub tracker.

Belbin: I agree that if github is used, alternatives are required

Endresen: An alternative could be to simply communicate the comment to the review manager - who copies the comment onto the issue tracking system? (Would comments then still always need to be identified to a person? Besides, a one-time-use email or github username is anyway easy to create...)

**Comment by baskaufs** [comment]
More discussion from Google doc, section 5.3 Public announcement:

Baskauf: OK, so here we have an inconsistency from above. It clearly states here that comments can be anonymous, but above it was a requirement that all submissions must be able to be associated with an identified individual.

Belbin: Indeed. A public review should permit  anonymous comments.

Endresen: Agree that an anonymity option is good -- but of course also to maintain the option to make signed comments. (Do we need an option where the identity is also anonymous to the review manager? I would guess not, and that anonymous comments could simply be communicated to the review manager).

Belbin: In theory, I can conceive of situations where comments may seek to be  anonymous to the Review Manager. Personally, I would argue against any such situation as any comments should at least be logged to the Review Manager. Commenters may be justified in anonymity to the public, but not the Review manager. In my research career, I always reviewed papers asking that my name as reviewer be attached to the review. I believe TDWG/BIS needs to encourage people to stand behind their comments, at least to the Review manager if not public.

Kampmeier: +1 --the possibility of anonymous public review needs to be an option, but the Review Manager needs to know from whom the comment is coming. This has Code of Conduct implications.

**Comment by dagendresen** [comment]
[Proposed some text updates to respective sections 3.3 and 4](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md).

**Comment by baskaufs** [comment]
Alright, I've re-read this thread and it seems like there is consensus with respect to anonymity of comments during the public review:

1. All comments should be made publicly available.
2. Commenters should be encouraged to sign their comments, either automatically through submission to a tracker or through their email to the Review Manager.
3. Anonymous comments would be permitted. The commenter may email them to the Review Manager and request that their comments be posted without their name. 

Although we've expressed concern about hard-coding specific technologies in these guidelines, I think at this point it would be unwieldy to try to manage comments without using an issues tracker. We would not necessarily need to specify that it be the GitHub tracker (although it probably would be), but I think it's the most reliable way for people to submit comments on their own and have them get automatically archived. Anyone one has trouble with the tracker would always have the option to email them to the review manager and have the review manager post them in the tracker on their behalf. We just recently concluded a pretty complicated public comment period in Darwin Core, leaning heavily on the issues tracker. There were some people with problems, but mostly they involved misunderstandings about the process, not the tracker technology. So I think we should go ahead and just specify that the public comments should be logged in an issue tracker.

I am going to proceed with making some edits under the assumption that we are in agreement on this and close this issue when I finish. If anyone objects, please re-open the issue and add further comments.

**Comment by Tasilee** [comment]
Thanks @baskaufs. I totally agree with the position of those three points. Also, given the almost universal dependency these days on GitHub, using the issue tracker as a default seems fair. As you say, if some are unable or unwilling then text can be sent to the Review Manager for incorporation.

**Comment by baskaufs** [comment]
OK, here are the edits I made that I believe resolve this issue:

https://github.com/tdwg/process/commit/088535e276711c912018863948f29ebce48b66b2
