### ISSUE TITLE
Form of tracking system for correspondence related to review process and expert reviews

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#5]
In the era of the OJS system, emails were supposed to be done through the system so that there would be a record of them. This was to allow a new review manager to take over in the event that a manager had to leave the post (which has happened) and also to guide future review managers who would need to know how the process works.

This could be simulated to some extent by using a private GitHub repo. That would keep the information private from the general public, but would not guarantee anonymity of the expert reviewers, as they would be visible to those who had access to the repo. However, that isn't really different from the OJS system, which allowed any review manager to look at any materials from previous reviews. So maybe that isn't a huge issue.

I do believe that in the interest of openness at least a summary of the public comments (minus those that were private) and the expert reviews (with reviewer identities removed) should be published along with the finished standard. This would make it clear to future users and maintainers of the standard what the considerations were that informed the final condition of the standard. See [this example](https://github.com/tdwg/ac/blob/master/historical/RecordOfPublicReview.md).

**Comment by gkampmeier** [comment]
What about using a form that could be scripted to upload to GitHub? I don't really understand how this is done, but I found the following [https://gist.github.com/anythingcodes/c68597c8e78541f703607d3cf324134a](https://gist.github.com/anythingcodes/c68597c8e78541f703607d3cf324134a) for a Google Form. (I also don't know if we have a GitHub Enterprise account @stanblum ), but we do have a Google account @WUlate as of last fall.  Whether using Google products is a barrier (I don't think you have to have a sign-on to fill in a form), or whether the same could be done with Survey Monkey (we have an account--looks like it may dump to a form? and thus a sheet?) or JotForm (we don't currently have a TDWG account, but JotForm will dump to a Google Sheet for a similar result, I would think)...?  Out of my depth here for the coding, but this could limit the number of people with access to the repo, although the security of Google products may need to be watched.

**Comment by dagendresen** [comment]
If using a private GitHub repo, or submitting (anonymously) through a form, would then the comments be openly visible to all at once? The expert review from the three expert reviewers would not be independent if they can see each other's comments before submitting their own comments. If we value independent expert review (which I think we do), this could be an issue?

**Comment by gkampmeier** [comment]
The [Darwin Core Hour](https://github.com/tdwg/dwc-qa) gives an example of using a [Google form](https://docs.google.com/forms/d/e/1FAIpQLSekd0QSdgiK5ujh6CLZPx9kKTcS-mJRNK_pGWk3b3fHv4x4gQ/viewform?c=0&w=1) to add issues to a repo.  Theirs is public and open, but I assume that the repo could be private (to the review manager and someone (@stanblum) on the [Process Interest Group](https://www.tdwg.org/community/process/)  until all reviews were in.  This would allow commenters both in the Independent and Public reviews to submit things directly to the Review Manager.  What it doesn't promote is discussion and risks pointing out the same potential flaws by multiple people.  Given that the Independent review requires independence (and possible anonymity) and is finished before the version for public review is offered, it is not unreasonable to say that a separate public repo (also available through form submission, but which may be watched by anyone for the public review.  Then offer direct communication with the Review Manager if someone feels that their comments need to be anonymous.  This to me should be the exception rather than the rule in an open community. We can also emphasize our [Code of Conduct](https://www.tdwg.org/conferences/2020/code-of-conduct/), which may need to modified/generalized for this purpose.

**Comment by baskaufs** [comment]
Sections of the document to be revised relevant to this issue:

[2 TDWG Standards Track line 61](https://github.com/tdwg/process/blob/master/review_manager.md#2-tdwg-standards-track)

[3.1 Reviewer Profile line 89](https://github.com/tdwg/process/blob/master/review_manager.md#31-reviewer-profile)

[5.2 Example of an email to potential reviewers line 209](https://github.com/tdwg/process/blob/master/review_manager.md#52-example-of-an-email-to-potential-reviewers)

**Comment by baskaufs** [comment]
Captured from discussion in Google doc:

Baskauf: again, OJS-specific, but perhaps should be replaced with updated instructions on how to archive the correspondence, e.g. in a private GitHub repo?

Belbin: The document needs to be self contained on the explicit required steps the Review manager needs to perform.

**Comment by baskaufs** [comment]
Comment from Google doc re: making submission available to solicited reviewer:

More discussion from Google doc:

Baskauf: I think that here there could be two alternatives: either an attached document  or a link to a Google doc or GitHub document (i.e. in Markdown). If the entire proposal is in GitHub, then the potential reviewer can just look at any parts they want. If a document is sent, at this point is it only the abstract as stated here? I'm not sure why the whole document(s) could not be sent if they are electronic anyway. 

If the documents are in Markdown, do they need to be converted into some format where comments can more easily be inserted (Google or Word doc)?

Belbin: As with the use of github, there is a need for at least an alternative

**Comment by Tasilee** [comment]
I'm more interested in the anonymity and privacy issues than the mechanism used for recording/tracking. 

Given that TDWG's default environment (that John, Stan and I designed by default) is 'open'/transparent, the default assumption should be for any correspondence to be open, linked to a person (email or maybe ORCID as the ID) and a date/time. TDWG should state this and promote this wherever (as in the CoC that @gkampmeier mentioned).

If, in the process of TDWG's business, someone wants to be anonymous, fine. This hopefully rare 'out' may be useful for TDWG to better achieve its goals. The point in the context of standards reviews is "Should anonymous reviews/comments be anonymous to the Review Manager"? I'd say "No" as we need to assume that the Review Manager may want or need to communicate with the author of the anonymous comments. One assumes that the person wanting to be anonymous, wants to remain so, unless we consider a 'sunset clause'. 

My feeling is that the correspondence surrounding the review be kept separate from, but linked to the the standards documents.

Back to the 'how': Markdown is less 'accessible' than Word or Google docs or even a text file. There isn't to my knowledge anything generic here. We will also subjected to evolving technology and applications/formats (e.g., OJS). The best we can do is provide guidance that will be the easiest for the majority of the TDWG catchment.

**Comment by baskaufs** [comment]
OK, I've re-read this and I think there are three separate issues:

1. keeping a record of correspondence with reviewers in case there needs to be a new review manager.
2. documenting the submitted expert reviews
3. documenting public comments. 

I'm going to defer on number 3; we can resolve it with issue #4. 

I think we've pretty much decided on the expert reviews (number 2 above): the default should be non-anonymous, the review manager has discretion on whether to report on them in a summary document or separately, the reviews themselves will be public. Whether or not they are published as part of a BISS article, I think PDFs of the reviews should get archived in the GitHub repo that's being used by the review manager along with the submitted drafts of documents, and any revisions. This will allow anyone who cares to examine the history of the submission process and how the final drafts were derived.

As for the first item, it seems like overkill to require archiving the correspondence between the review manager and the expert reviewers. I would suggest that we specify that the review manager needs to keep a record of the correspondence sufficient for a replacement review manager to take over. Once the standard is ratified, it is hard for me to see why anyone would care to see this correspondence. In my mind, this is different from correspondence related to the public commentary -- all official comments should be documented. But the important part of the expert review stage is the review itself, not the correspondence between the review manager and the reviewer. The key thing is for any replacement review manager to know the names and timing of review requests, so that they can know if reviewers are taking too long and to avoid re-asking a possible reviewer who has already declined if a replacement reviewer is needed.

If we concerned about a review manager dropping dead or flaking out, I suppose we could specify that they keep the record of correspondence in some shared place in the cloud (Dropbox, Box, Google Drive) where it could be retrieved/examined if disaster happened and a replacement review manager would be required. Unless we really think this all needs to be permanently archived, I wouldn't recommend GitHub because of the complexity of scrubbing information about the reviewers who might potentially be anonymous. Also, the public doesn't really need to know who all was asked and declined to review. 

I've made some edits to the draft reflecting this approach. Please take a look and suggest alternative text or additions. The diff is [here](https://github.com/tdwg/process/commit/00d83564b4f26c97028d7a5f80f83c354e14ca43#diff-1b571d9e461845b8613559351ada73c70991f9bea2a95500c10d2bb50bd0cd4b)

**Comment by Tasilee** [comment]
Thanks @baskaufs. 

- Reviews in the GitHub repo sounds fine.
- "the review manager needs to keep a record of the correspondence sufficient for a replacement review manager to take over" also seems very reasonable. Unless there was an unusual situation, one would assume there will be little 'back and forth'. If a new Review Manager had to take over, then the main issues are the dates of requests and receipts and the reports. Again, we only want to be prescriptive on issues where it is deemed mandatory.
- Permanent archive: We need to aim for it using best current practice, but it is an evolving target.

**Comment by gkampmeier** [comment]
"If we concerned about a review manager dropping dead or flaking out, I suppose we could specify that they keep the record of correspondence in some shared place in the cloud (Dropbox, Box, Google Drive) where it could be retrieved/examined if disaster happened and a replacement review manager would be required."

TDWG currently has a Google Drive account (created last year mainly for uploading conference materials from authors and downloading by Pensoft for linking to abstracts--a limited number of people on the Exec have full privileges) but to my knowledge, TDWG does not have a Dropbox or Box account, both of which are more secure than Google Drive in terms of discovering and viewing possibly sensitive information (people contacted; reports). 

I don't use my Dropbox or even my Box account (through Univ. IL) enough to know what to recommend and how best to use it, but in looking at my Dropbox, I see files from TDWG's 2013 Exec and (some) presentations from that meeting. Neither folder belongs to me but I have edit privileges. While all of these systems are evolving targets and aiming for best current practice should be the goal, TDWG itself should probably create the space and current recommended best practice in this case so we don't have to worry where to look if a review manager is hit by a bus.

**Comment by dagendresen** [comment]
I think that simply: _"The Review Manager should keep a record of correspondence with potential and engaged expert reviewers that would be sufficient for a replacement Review Manager to take over if that became necessary."_ is sufficient -- and that the very extreme situation where a Review Manager drops dead is not required to be addressed in these guidelines :-)

**Comment by baskaufs** [comment]
I think that ensuring continuity across review managers is important, but I agree that that is a problem beyond the scope of this document. Perhaps when a draft of this is ready to be shared with the Executive, we can mention this issue as something for them to manage as part of their operating procedures.

**Comment by baskaufs** [comment]
I think this is ready to be closed
