### ISSUE TITLE
What are mechanisms to alert the community of the status of public review?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#6]
At the time the Review Manager Guidelines were written, nearly all discussion in the community took place on the tdwg-content email listserv. That list still exists, but has little traffic and I think many people do not know that it exists, nor how to get on it. We have a newsletter, but I'm not sure how the distribution of it is controlled. People may be "watching" GitHub repos, but some people don't have GitHub accounts nor understand that notification mechanism. There is also Twitter and a number of email lists (taxacon,etc.) that are tracked by some constituencies in the community.

It seems like including a list of places to notify within the review manager document would be likely to make it outdated. What is the alternative? Perhaps have a list on a public page on the TDWG website (near or associated with the Review Manager Guidelines) that could be more actively maintained. Making that list public would both allow the community to suggest additional ways to communicate, and also could inform the community of what the communication mechanisms are and how they can join them (i.e. have instructions with each item how to join).

**Comment by gkampmeier** [comment]
This seems to be a discussion that is also appropriate for the outreach & communications subcommittee, now headed by @mhirschfeld (this is an experiment to see if Mareike Petersen is actually pinged, even though I got this handle elsewhere).  Mareike has taken over the TDWG Twitter account; I (and a few others including @stanblum) are administrators on the TDWG Facebook account; @stanblum usually sends out periodic emails from our MailChimp account (was this the newsletter you were referring to?), and of course the TDWG lists...@debpaul just made use of the tdwg@lists.tdwg.org to distribute a broad reminder about the 2021 Program Committee deadline (today). How that list differs from the MailChimp list...? I am not sure who exactly controls these listserves.

**Comment by baskaufs** [comment]
Yes, Stan's MailChimp mailings was what I meant. 

At least many years ago I think @timrobertson100 was running the list.tdwg.org at least with respect to tdwg-content@list.tdwg.org .  I would be curious to know the size of the distribution on tdwg@lists.tdwg.org - I don't think I'm on that list (I'm on tdwg-content, which is where I expect things to come from).

**Comment by baskaufs** [comment]
Relevant sections of document:

[Section 4 Public Review, line 131](https://github.com/tdwg/process/blob/master/review_manager.md#4-public-review)

**Comment by baskaufs** [comment]
Discussion captured from the Google doc:

Baskauf: With the decline of the tdwg-content email list, there no longer seems to be an "authoritative" way to communicate this kind of information to the community. There is a newsletter, but not every one gets it. The last public review of a new standard was missed by some key people in TDWG who missed seeing it. Perhaps there should be a list of recommended venues, including Twitter, tdwg-content, GitHub issues trackers, and ???

Belbin: A mix of push and pull is warranted.

**Comment by tucotuco** [comment]
I would recommend also:

TDWG Facebook
Biodiverstty Informatics Training Curriculum Facebook (
https://www.facebook.com/groups/BiodiversityInformatics/)
Taxacom list (http://mailman.nhm.ku.edu/cgi-bin/mailman/listinfo/taxacom)

**Comment by baskaufs** [comment]
Discussion related to who makes the announcement about public comment (regarding section 5.3, example of Public Review Announcement)

Baskauf: Inclusion of this document here implies that although the Executive decides when to advance to Public Comment, the Review Manager actually makes the announcement. However, I'm not sure there has been consistency about this. In at least one case, I think someone made the announcement on behalf of the Executive. 

I feel like it would be good to explicitly state that it is the Review Manager's job to make this announcement. Previously it was noted that it is important that the review manager be seen as in independent and unbiased player in the process. Having the Review Manager send the notifications would be consistent with that concept.

Belbin: I fully agree: The announcement should be left to the Review Manager.

**Comment by dagendresen** [comment]
Maybe add a line in the guideline that the "Announcement" should include a line similar to:
> feel free to distribute this announcement of public review in your relevant network

Rather than aiming at enumerating all the possible social media channels, that we can think of? (Which would be bound to miss some). And it might perhaps not be reasonable to demand that the Review Manager must have a user account on all the respective social media platforms that could be enumerated here?

**Comment by gkampmeier** [comment]
While it is totally appropriate (and no doubt appreciated) that the Review Manager (RM) create the announcement, it should not be up to that person to distribute it.  As this discussion has pointed out, there are multiple outlets used, none really "authoritative" in the sense of getting everyone who might be interested in the news. I would argue that the Outreach and Communication function subcommittee (part of the TDWG Exec) in conjunction with the Secretary/Secretariat @stanblum @thearyung should use the announcement created by the RM to distribute (and encourage distribution in affected discipline communities) the announcement (creating/updating a checklist of usual suspects).

**Comment by Tasilee** [comment]
I agree with @gkampmeier that announcements should be prompted from the Review manager to the Outreach and Communications subcommittee. It simplifies the issue and allows for ongoing flexibility.

**Comment by dagendresen** [comment]
Maybe both an announcement from the Review Manager (to the TDWG email list?) & coordinated outreach from the TDWG Outreach and Communications subcom is useful?? Note also that public comments should be directed to the Review Manager.

**Comment by mhirschfeld** [comment]
Thanks for bringing this up. Outreach and Communication should coordinate this together with the review manager and help to reach out to a broader community. @dagendresen suggestion to add a paragraph that the announcement can be shared in relevant networks are also usefull. How many people are we reaching with the Email lists (tdwg-content, mailchimp)?

**Comment by baskaufs** [comment]
After reviewing this thread and thinking about how things went with the recent marathon Darwin Core public comment, I think the solution is to specify that the Review Manager should prepare the announcement in their own name, but that Outreach and Communication subcommittee should take responsibility for the distribution of the announcement. The functional subcommittee structure is now written into the [TDWG constitution](https://www.tdwg.org/about/constitution/) with officially designated chairs, so it seems safe to enshrine this in the document.

With the DwC public review, the announcement was in the form of a news item. Since it had a good URL, the O&C subcommittee could easily Tweet/FaceBook/Slack, etc. the link to the announcement on behalf of TDWG itself. That would not preclude anyone else (including the Review Manager) from retweeting or sharing the link in their own networks. So specifying that the O&C create an announcement on an official web platform and publicize it should work. 

OK, just reviewed the [process document](https://www.tdwg.org/about/process/#ratification%20of%20standards_1) and here's what it says:

> Public Review. The Executive Committee directs the Proposed Standard to be placed in the TDWG repository, publishes a request for comment (RFC) that describes facilities for, and duration of public comment. A minimum of 30 days must be allowed for comment. At the end of the comment period, the Task Group may modify the specification or its documentation as necessary. Any subsequent submission should address the comments received in the public review.

So archiving the proposal in the TDWG repository is a requirement (although that doesn't preclude publishing it elsewhere, e.g. BISS). It also says that the Executive Committee publishes an RFC. Since the functional subcommittee chairs are members of the executive, specifying that the chair publish the announcement (i.e. RFC) would comply with this requirement as well. 

I'm going to press on with revising the document with these things in mind.

**Comment by gkampmeier** [comment]
I think this is missing a couple of words:
The Executive Committee directs _that_ the Proposed Standard ~~to~~ be placed in the TDWG repository, _then_ publishes a request for comment (RFC) that describes facilities for, and duration of public comment.

**Comment by baskaufs** [comment]
@gkampmeier I agree. I have no idea how one makes a change to the Process document (i.e. the by-laws of TDWG). This seems to be a trivial clarification, so I suppose the Executive could just direct someone to make the edit.

**Comment by gkampmeier** [comment]
@baskaufs I didn't fully realize that this wasn't part of our documentation. @stanblum maybe you can help guide us on who tweaks language in the Process document (see above about the public review and clarifying edits) and whether it requires anything official (or can it just be done?).

**Comment by baskaufs** [comment]
Here is my attempt at revisions: https://github.com/tdwg/process/commit/0dcb2649113b78897d8dd2c537e0878e3057ec55

I feel like the example announcement is a bit cobbled together, so if someone with better editing skills can clean it up, that would be great. After comparing with the historical examples, I think it has the key features at least.

**Comment by baskaufs** [comment]
There have been a number of edits since this, so I'm presuming that we've worked this one out.
