### ISSUE TITLE
Assemble examples of communications related to past public reviews

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#7]
For reference purposes and to help in the revision of the Review Manager Guidelines, it would be good to have a record of the text of emails or other notifications that were sent out to the community to announce the start of public comment (and perhaps other stages of the review). 

We could use these to revise the example Public Review Announcement in the guidelines.

I think most of these (except perhaps the most recent) would be in the [history of tdwg-content](http://lists.tdwg.org/pipermail/tdwg-content/)

**Comment by baskaufs** [comment]
<http://lists.tdwg.org/pipermail/tdwg-content/2009-October/000276.html>

**[tdwg-content] Public Review of GUID and LSID Applicability Statement**

TDWG is pleased to announce the commencement of the Public Review of the Globally Unique Identifier (GUID) and Life Sciences Identifier (LSID) Applicability Statements. Applicability Statements provide guidance for use of external standards within the TDWG domain. The GUID statement provides general recommendations and the LSID one covers the specific GUID currently recommended by TDWG. Since being officially submitted, the Applicability Statements have undergone a peer review, a review by the TDWG Executive and multiple revisions.

Open Invitation: We invite all who may contribute and/or consume biodiversity information to examine this proposed applicability statement during the Public Review period from 23rd October till at least 23rd November 2009.

How to Participate: You can participate in the review of the GUID-LSID AS in two ways; either through lodging a comment through TDWG’s Open Journal System, or you can take the Microsoft Word document and edit it with track changes and resubmit it to the GUID-LSID AS Wiki space.

You can post comments to the Open Journal System (which may be anonymous) at http://www.tdwg.org/stdtrack/article/view/150. The abstract is displayed and on the right hand side of the page is a link to add a comment. Please note: you must be registered and logged in to the TDWG web site to post a comment, however registration is free. Down the bottom of the page, there is a link to download the complete applicability statement.

You can also comment direct in a copy of the document as follows:

- At the previous URL, download a copy of the Microsoft Word format document.

- Once you have downloaded it, turn on track changes and make your notes and comments.

- Submit that file at http://wiki.tdwg.org/twiki/bin/view/GUID/GUIDAndLSIDASReview.

Please DO NOT add any comments to the Wiki page, comment only through the two methods outlined above.
Questions about the process should be directed to me at ben(dot)richardson(at)dec.wa.gov.au.
Please share this opportunity for public comment and review with others you think may be interested.
Acknowledgements: I’d like to thank the authors, the anonymous reviewers and the members of the Executive Committee for their contribution to the document. In addition, the guidance of Lee Belbin through the review process has been invaluable and greatly appreciated.

Links:

- GUID and LSID AS comment area in OJS http://www.tdwg.org/stdtrack/article/view/150.

- LSID Wiki space: http://wiki.tdwg.org/twiki/bin/view/GUID/GUIDAndLSIDASReview

- LSID Resolution Project home page: http://lsids.sourceforge.net/

- LSID Specification: http://lsids.sourceforge.net/quick-links/lsid-spec/

Please accept my apology if you’ve received this multiple times from various mailing lists.
Regards,
Ben Richardson

**Comment by baskaufs** [comment]
Forwarded in <http://lists.tdwg.org/pipermail/tdwg-content/2009-July/000436.html>

**[tdwg] TDWG: Public Review of the Darwin Core 'standard'**

From: tdwg-bounces at lists.tdwg.org [mailto:tdwg-bounces at lists.tdwg.org] On Behalf Of Lee Belbin
Sent: Saturday, 11 July 2009 11:09 a.m.
To: tdwg at lists.tdwg.org; Taxacom at mailman.nhm.ku.edu
Subject: [tdwg] TDWG: Public Review of the Darwin Core 'standard'

Apologies for cross posts - and please feel free to distribute this
announcement to all relevant communities.

TDWG is pleased to announce the commencement of the Public Review of Darwin
Core - a standard for sharing biodiversity information. You will find the
proposed standard is a living document with a history, an anchor in the
Dublin Core, and mechanisms to grow and change. Since being officially put
forward as a draft standard in February 2009, Darwin Core has undergone a
peer review, a review by the TDWG Executive, and multiple revisions.

Open Invitation: We invite all who may contribute and/or consume
biodiversity information to examine this proposed standard during the Public
Review period from 11th July through at least 10th  August 2009.

How to Participate: Visit the Darwin Core Progress site
(http://code.google.com/p/darwincore/wiki/DarwinCoreProgress) for the latest
background information on the process and critical links to content
(http://rs.tdwg.org/dwc/index.htm) and participation.  To discuss ideas with
others or offer comments that are not targeted for action, please subscribe
(http://lists.tdwg.org/mailman/listinfo/tdwg-content) and contribute to the
tdwg-content mailing list (tdwg-content(at)lists.tdwg.org).  Recommended
actions or issues should be submitted to the Issue Tracker of the Darwin
Core (http://code.google.com/p/darwincore/wiki/SubmittingIssues) so that
they may be assigned, prioritized, and tracked.  This Public Review process
will be archived along with all other documentation in the TDWG Standards
Track.  Questions about the process should be directed to the Review
Manager, Gail Kampmeier (gkamp(at)illinois.edu).

Please share this opportunity for public comment and review with others you
think may be interested.

Acknowledgements: As Review Manager, I would like to express my gratitude to
the authors, John Wieczorek, (MVZ), Markus Döring (GBIF), Renato De Giovanni
(CRIA), Tim Robertson (GBIF), Dave Vieglais (KUNHM) for the enormous efforts
made in bringing the Darwin Core standard to this point; to the initial
anonymous peer reviewers, and to Lee Belbin and the rest of the TDWG
Executive for their advice, support, and encouragement in this process; and
to GBIF for tipping the scales by bringing together the authors in a
workshop that led to this submission.

Links expanded:
Darwin Core Progress -
http://code.google.com/p/darwincore/wiki/DarwinCoreProgress
Darwin Core content - http://rs.tdwg.org/dwc/index.htm
Subscribe to tdwg-content  -
http://lists.tdwg.org/mailman/listinfo/tdwg-content
Issue Tracker - http://code.google.com/p/darwincore/wiki/SubmittingIssues

Related Links:
TDWG: http://www.tdwg.org/
Other TDWG Standards: http://www.tdwg.org/standards/
TDWG Standards Track (in OJS): http://www.tdwg.org/stdtrack/index
Dublin Core's Metadata Initiative in Science:
http://ils.unc.edu/spaces/sam/index.php/Main_Page

Sincerely,
Gail E. Kampmeier, Review Manager
Illinois Natural History Survey, Institute of Natural Resource
Sustainability, University of Illinois at Urbana-Champaign, 1816 South Oak
St., Champaign, Illinois 61820 USA email: gkamp(at)illinois.edu


Lee Belbin
TDWG Secretariat


_______________________________________________
tdwg mailing list
tdwg at lists.tdwg.org
http://lists.tdwg.org/mailman/listinfo/tdwg

**Comment by baskaufs** [comment]
<http://lists.tdwg.org/pipermail/tdwg-content/2013-March/002962.html>

**[tdwg-content] Audubon Core Public Review**

Steve Baskauf steve.baskauf at vanderbilt.edu
Sat Mar 2 17:04:01 CET 2013

(Apologies for any cross-listing)

Audubon Core Public Review
 
By: Steve Baskauf, Review Manager
 
Biodiversity Information Standards (TDWG) announces the Public Review of 
the proposed Audubon Core Multimedia Resources Metadata Standard. 
Audubon Core is designed to provide a controlled vocabulary to address 
the management, acquisition, and content descriptions of biodiversity 
multimedia.  It is a product of the Joint GBIF- TDWG Multimedia 
Resources Task Group (MRTG) and has undergone peer review, several 
revisions, and review by the TDWG Executive Committee.  If you are a 
potential producer or consumer of metadata for biodiversity-related 
multimedia, we would like your input on this proposed TDWG Technical 
Specification Standard.
 
You may find it easiest to view the proposed standard online.  The 
following links lead to the three parts of the standard:
 
- the non-normative introduction: 
http://terms.gbif.org/wiki/Audubon_Core_Non_Normative_Document
- the normative introductory material: 
http://terms.gbif.org/wiki/Audubon_Core_(1.0_normative)
- the normative term list: 
http://terms.gbif.org/wiki/Audubon_Core_Term_List_(1.0_normative)
 
A downloadable zip archive containing the proposed standard can be 
obtained at http://www.tdwg.org/standards/638/ .  This archive includes 
an informative adoption and sustainability plan which is not an official 
part of the proposed standard.
 
To raise specific issues or to make specific recommendations, use the 
issues tracker described at 
http://code.google.com/p/auduboncore/wiki/AboutIssueTracker .  To engage 
in general discussion about the standard, join the TDWG email list 
(tdwg-content) by subscribing at 
http://lists.tdwg.org/mailman/listinfo/tdwg-content .  You can then post 
messages to tdwg-content at lists.tdwg.org .  Issues raised in that 
conversation may be added to the issue tracker as well.  Comments about 
the proposed standard will be archived as a part of the standards 
adoption process.
 
In accordance with the TDWG standards process, a minimum of 30 days is 
required for public comment on the proposed standard. Comments should 
therefore be received by 1st April 2013. For more information about the 
TDWG standards process, see 
http://www.tdwg.org/standards/status-and-categories/ and 
http://www.tdwg.org/about-tdwg/process/ .
 
Please distribute this call for comment to anyone you think could or 
should comment on Audubon Core.  You may address any questions about the 
review process to me at steve.baskauf at vanderbilt.edu .
 
Thanks to the authors, Robert A. Morris (convenor), Vijay Barve, Mihail 
Carausu, Vishwas Chavan, Jose Cuadra, Chris Freeland, Gregor Hagedorn, 
Patrick Leary, Dimitry Mozzherin, Annette Olson, Greg Riccardi, and Ivan 
Teage for their work on the proposed standard. Thanks also to the 
anonymous reviewers, the Executive Committee, and Lee Belbin who served 
previously as Review Manager for the standard.

-----
<http://lists.tdwg.org/pipermail/tdwg-content/2013-April/002976.html>

**[tdwg-content] Completion of Audubon Core public review**

Steve Baskauf steve.baskauf at vanderbilt.edu
Thu Apr 25 21:27:04 CEST 2013

More than the minimum 30 days required for the public review of Audubon 
Core have passed and I've received comments from everyone who told me 
that they planned to comment.  I am therefore closing the public review 
period.  The review guidelines at  
http://www.tdwg.org/fileadmin/documentation/guidance_docs/ReviewManagerGuidelines.doc 
require that Public Review comments be visible to all.  Since many of 
the comments I received were emailed directly to me rather than to the 
tdwg-content list or posted on the Issues Tracker, I've posted a digest 
of the comments at 
http://code.google.com/p/auduboncore/wiki/RecordOfPublicReview for 
public inspection.

As a result of these comments, a number of issues have been opened by 
commenters or by me based on the submitted comments.  These issues can 
be viewed at the Audubon Core Issue Tracker 
http://code.google.com/p/auduboncore/issues/list

I would like to thank everyone who took the time to read the 
specification and comment.  I think that the standard will be 
strengthened based on your comments and look forward to working with the 
authors to implement many of your suggestions.

Steve Baskauf
Audubon Core Review Manager

-- 
Steven J. Baskauf, Ph.D., Senior Lecturer
Vanderbilt University Dept. of Biological Sciences

**Comment by baskaufs** [comment]
I found this at <http://lists.tdwg.org/pipermail/tdwg-content/2017-February/003690.html> but from its text, it looks like it may be an abbreviated announcement based on one in the "TDWG Announcements" newsletter (don't remember what that is).

**[tdwg-content] Public review for TDWG Vocabulary documentation and maintenance standards**

Dag Endresen dag.endresen at gmail.com
Mon Feb 27 10:30:27 CET 2017

Hi everyone,

A brief reminder to participate in the public review
<https://github.com/tdwg/vocab/blob/master/README.md> for the Vocabulary
documentation and maintenance standards - as announced with the TDWG
Announcements newsletter last week.

The Documentation Specification will proscribe the format of human- and
machine-readable documents that form TDWG (vocabulary) standards. The
Vocabulary Maintenance Specification proscribes the process by which TDWG
vocabularies will be modified and amended.

https://github.com/tdwg/vocab/blob/master/README.md

Please submit any comments, questions, or criticisms as "issues" in the
issue tracker. If you would like to register an issue anonymously, please
send it via email to the review manager, Dag Endresen
<dag.endresen at gmail.com?subject=Issue%20with%20Vocabulary%20standards>.
Public review will be open at least through March 27th, and may be extended
if a valuable discussion is on-going.

https://github.com/tdwg/vocab/issues

(sorry for cross-posting)

----
See also <https://github.com/tdwg/vocab/blob/master/expert-review-materials/TDWG-VOCAB-expert-review-report-v20161113.pdf> which is a very organized summary of the expert review.

**Comment by baskaufs** [comment]
The GGBN and ABCD-EFG public reviews were not announced on tdwg-content July 2020. There were, in fact, no posts to tdwg-content the entire month, which I guess says something about the traffic there. The following is a text that I received via direct email. I am not aware of a record of it anywhere online, although there is a "view in your browser" link to MailChimp: <https://mailchi.mp/e4d3a358b3af/tdwg-standards-update-30-day-public-reviews-open-for-two-draft-standards-ggbn-and-abcd-efg?e=5917438abb>

**TDWG Standards Update: 30-day public reviews open for two draft standards, GGBN and ABCD-EFG**

From: TDWG Secretariat <secretariat@tdwg.org>
Reply-To: TDWG Secretariat <secretariat@tdwg.org>
Date: Wednesday, July 1, 2020 at 9:33 PM
To: Steve Baskauf <steve.baskauf@Vanderbilt.Edu>
Subject: TDWG Standards Update: 30-day public reviews open for two draft standards, GGBN and ABCD-EFG

![image](https://user-images.githubusercontent.com/5765781/107601347-0da05f80-6bec-11eb-8e16-dba7f02fc84c.png)

![image](https://user-images.githubusercontent.com/5765781/107601369-20b32f80-6bec-11eb-973f-2171aa812e21.png)

----

As I noted in my comments at https://github.com/tdwg/ggbn/issues/3, there is no information about who the review manager(s) were nor who were on the Task Groups. 

I believe that the GGBN standard was not ratified or is in limbo. I believe that the EFG "standard" was ratified, but as a supplement to ABCD (a "2005" standard), it isn't exactly clear to me what its status is. It does not appear on the [TDWG Standards page](https://www.tdwg.org/standards/). I also don't know who maintains it, since ABCD doesn't have a maintenance group.

**Comment by dagendresen** [comment]
The [February 2017 Newsletter](https://us9.campaign-archive.com/?u=50f3cc44307841383062ca0d6&id=6f626d304b&e=d762e08a1e) announced the public review for the vocabulary standards.

> <sup>Feb 2017 announcements:  Call for subcommittee volunteers; TDWG Community Support Fund; Public review opens for vocabulary standards.</small> [View this email in your browser](https://us9.campaign-archive.com/?u=50f3cc44307841383062ca0d6&id=6f626d304b&e=d762e08a1e)</sup>

(...)

> ### Public Review Begins for our Draft Vocabulary Documentation and Maintenance Standards
> In 2015, the Vocabulary Specification Task Group was established, with Steve Baskauf as Convener, and charged with developing specifications for documenting and maintaining vocabulary standards. The Documentation Specification will proscribe the format of human- and machine-readable documents that form TDWG (vocabulary) standards, and will supersede the current unratified draft specification for documenting a standard. The Vocabulary Maintenance Specification proscribes the process by which TDWG vocabularies will be modified and amended. That specification was based on the current Change Policy of the Darwin Core Namespace, and what has been learned from its application. If ratified, it will apply to all current and future TDWG vocabularies. These draft standards passed expert review last Fall and are now ready for public review.  Please find the specifications and the supporting documents in [Vocab repository](https://github.com/tdwg/vocab/) of our GitHub site.  Begin with the [README.md](https://github.com/tdwg/vocab/blob/master/README.md) file. Please submit any comments, questions, or criticisms as "issues" in the [issue tracker](https://github.com/tdwg/vocab/issues). If you would like to register an issue anonymously, please send it via email to the review manager, [Dag Endresen](mailto:dag.endresen@gmail.com). Public review will be open at least through Mar 27th, and may be extended if a valuable discussion is on-going. The results of public review will be summarized and published shortly thereafter.

**_TDWG Announcements_** newsletter was distributed by MailChimp.

**Comment by baskaufs** [comment]
Relevant sections of document:

[Section 5.3 Example of Public Review Announcement, entire section](https://github.com/tdwg/process/blob/master/review_manager.md#53-example-of-public-review-announcement)

**Comment by baskaufs** [comment]
I've created primitive Markdown copies of these emails and links, pushed them to the repo, and linked to them at the end of the draft.
