### ISSUE TITLE
Grant edit access of this repo to persons revising the Review Manager Guidelines

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#8]
@stanblum @peterdesmet I have prepared a [Markdown revision of the Review Manager Guidelines](https://github.com/baskaufs/process/blob/main/review_manager.md) with website styling and would like to push it here so that I can link the issues in the `process` repo tracker to the parts of the doc that still need to be fixed. Can you please grant at least temporary push access to this repo to me, @gkampmeier, @dagendresen, and @Tasilee so that they can work on the draft here with me?

**Comment by peterdesmet** [comment]
Hi @baskaufs I have created a @tdwg/process team with you 4 and @stanblum. You through that team you now have admin rights to this repo.

**Comment by baskaufs** [comment]
Thanks, @peterdesmet
