### ISSUE TITLE
Revise recommendation about file formats used during the review process

### ISSUE THREAD

**Issue by baskaufs** [tdwg/process#9]
The prior recommendation was to use Word with track changes. We need to decide whether nothing should be suggested (to avoid making the doc obsolete) or give examples but leave it up to the manager.

**Comment by baskaufs** [comment]
Relevant sections of document:

[Section 2 TDWG Standards Track, line 67](https://github.com/tdwg/process/blob/master/review_manager.md#2-tdwg-standards-track)

**Comment by baskaufs** [comment]
Comments captured from Google doc:

Baskauf: I think that these points may be too specific and could probably be left to the review manager and reviewers to decide. I suspect that both Google Docs and Word docs with track changes may be usable options.

Belbin: I agree. If something isn't specifically required, don't mention it.

Endresen: The suggested open formats listed here already look very dated...

**Comment by gkampmeier** [comment]
My recommendation would be to balance leaving this flexible for the Review Manager to work (as we've seen tools evolve and some die), while expressing expectations of what kinds of features (e.g., ability to track changes, comment) should be used, and perhaps guidance on making reviewers aware that their use of these tools should be anonymous.  The specifics of achieving this last part (anonymity) is something that changes potentially way too fast (just try googling a how to) to even include in an appendix. Perhaps stating that specific guidance can be provided at the initiation of the review process.

**Comment by dagendresen** [comment]
Propose to remove details on file formats - as indicated with strikethrough in section 2, [revisions_round1/review_manager.md](https://github.com/tdwg/process/blob/revisions_round1/review_manager.md)

**Comment by baskaufs** [comment]
Deleted text about file formats as suggested. Added text advising making the material available to reviewers in a form where comments and changes can be tracked while also archiving a PDF of the original submission. See [this diff](https://github.com/tdwg/process/commit/a1ac45b5de9f4d8e59a62415d966ddb1c5e6d515#diff-1b571d9e461845b8613559351ada73c70991f9bea2a95500c10d2bb50bd0cd4b) for the change.

**Comment by Tasilee** [comment]
Sounds reasonable to me.
